payment-provider:
  url: "http://192.168.0.18:7902"
  session-timeout: 300000
application:
  input-file: "sample-input.csv"
  output-file: "output.csv"
  callback-url: "http://192.168.0.12:8080"
credentials:
  account-id: "SEGOVIA"
  key: "0aVp83wuFp6wjvQ3"
