payment-provider:
  url: "http://192.168.0.18:7902"
  session-timeout: 300000
application:
  input-file: "/var/opt/segovia/payments.csv"
  output-file: "/var/opt/segovia/output.csv"
  callback-url: "http://192.168.0.18:8080"
credentials:
  account-id: "SEGOVIA"
  key: "0aVp83wuFp6wjvQ3"
