payment-provider:
  url: "http://host.docker.internal:7902"
  session-timeout: 300000
application:
  input-file: "/var/opt/input.csv"
  output-file: "/var/opt/output.csv"
  callback-url: "http://host.docker.internal:8080"
credentials:
  account-id: "SEGOVIA"
  key: "0aVp83wuFp6wjvQ3"
